### ISSUE TITLE
[KDE] Taru-Dark pack makes some icons very hard to see

### ISSUE THREAD

**Issue by ivanno4317** [kuroehanako/Taru-icons#1]
Some icons with Taru-Dark are very hard to see. 

In this screenshot of kdevelop, while Taru-dark is applied, some icons are nearly invisible. 
![image](https://user-images.githubusercontent.com/75901734/172408789-8d6d1630-43df-4ad3-9277-17209f07cb48.png)

I've checked inside Taru-Dark icon folder and the icon run-build.svg appears white. So i don't understand why in kdevelop the icon is dark grey.

With other icon packs the icon appears white, as it should.

**Comment by mjkim0727** [comment]
I added breeze-dark inherits for temporary solution.
